apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kube-auth-proxy-egress
  namespace: openshift-ingress
spec:
  podSelector:
    matchLabels:
      app: kube-auth-proxy
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 6443
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-kube-apiserver
          podSelector:
            matchLabels:
              app: openshift-kube-apiserver
    - ports:
        - port: 5353
          protocol: TCP
        - port: 5353
          protocol: UDP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-dns
